name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint:all
      - name: Build
        run: yarn build
      - name: Test
        run: yarn cover
        env:
          CI: true
      - name: Report coverage
        if: matrix.node-version == '14.x'
        run: yarn codecov
        env:
          CI: true
